name: Build APK

on:
  push:
    paths-ignore:
      - 'README.md'

    branches:
      - master
      - actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build

      - name: Update Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build app
        run: ./gradlew build

      - name: List build folder
        run: ls app/build/outputs/apk/

      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: gbcc
          path: app/build/outputs/apk/
